name: Perform integration testing
on: [push, pull_request]

jobs:
  get_changed_json_files:
    runs-on: ubuntu-latest
    name: Get changed files

    outputs:
      any_changed: ${{ steps.changed-files.outputs.any_changed }}
      all_changed_files: ${{ steps.changed-files.outputs.all_changed_files }}

    steps:
      - uses: actions/checkout@v4

      - name: Get changed JSON files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files: |
            **.json

  upload_and_test:
    needs: get_changed_json_files
    if: needs.get_changed_json_files.outputs.any_changed == 'true'
    env:
      CHANGED_FILE: ${{ needs.get_changed_json_files.outputs.all_changed_files }}
    runs-on: ubuntu-latest
    name: Upload and test changed files

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          sudo apt-get install -y aha

      - name: Get or create a DNAnexus project for testing
        id: get-create-project
        run: |
          echo "${CHANGED_FILE} was changed in this PR"
          dx login --token ${{ secrets.DX_TOKEN }} --noprojects
          python get_or_create_testing_project.py -i ${CHANGED_FILE} -o dx_project_id.txt
          TEST_PROJ_ID=$(cat dx_project_id.txt)
          echo "TEST_PROJ_ID=$TEST_PROJ_ID" >> $GITHUB_OUTPUT

      - name: Upload changed JSON config file to testing_project
        env:
          TEST_PROJ_ID: ${{ steps.get-create-project.outputs.TEST_PROJ_ID }}
        id: upload-config
        run: |
          FILE_ID=$(dx upload ${CHANGED_FILE} --destination ${TEST_PROJ_ID}:/ --brief)
          echo "Config file uploaded. File ID: $FILE_ID"
          echo "FILE_ID=$FILE_ID" >> $GITHUB_OUTPUT

      - name: Get production config in DNAnexus and output JSON with config info
        env:
          UPLOADED_FILE_ID: ${{ steps.upload-config.outputs.FILE_ID }}
        run: |
          python get_production_config.py -i ${CHANGED_FILE} -f ${UPLOADED_FILE_ID} -p ${{ vars.CONFIG_PATH }}}

      - name: Generate diff report compared to production config
        env:
          UPLOADED_FILE_ID: ${{ steps.upload-config.outputs.FILE_ID }}
        run: |
          PROD_CONFIG_ID=$(jq -r .prod.dxid config_diff.json)
          PROD_CONFIG_NAME=$(jq -r .prod.name config_diff.json)
          UPDATED_CONFIG_NAME=$(jq -r .updated.name config_diff.json)

          icdiff --unified=3 --line-numbers <(dx cat ${PROD_CONFIG_ID}) -L ${PROD_CONFIG_NAME} <(dx cat ${UPLOADED_FILE_ID}) -L ${UPDATED_CONFIG_NAME} | COLUMNS=100 aha > config_diff.html
          echo "Diff report generated"
      - uses: actions/upload-artifact@v4
        with:
          name: diff-report
          path: config_diff.html
