name: Perform integration testing
on:
  push:
  workflow_dispatch:

jobs:
  upload_and_test:
    runs-on: ubuntu-latest
    name: Upload and test changed files
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          sudo apt-get install -y aha

      - name: Get changed JSON files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files: |
            **.json

      - name: Upload changed JSON files to DNAnexus
        id: changed-config
        if: steps.changed-files.outputs.any_changed == 'true'
        env:
          CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          dx login --token ${{ secrets.DX_TOKEN }}
          echo "${CHANGED_FILES} was changed in this PR"
          FILE_ID=$(dx upload ${CHANGED_FILES} --destination ${{ vars.TESTING_PROJECT }}:/ --brief)
          echo "Config file uploaded. File ID: $FILE_ID"
          echo "FILE_ID=$FILE_ID" >> $GITHUB_OUTPUT

      - name: Get production config in DNAnexus and output JSON with config info
        if: steps.changed-files.outputs.any_changed == 'true'
        env:
          CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
          UPDLOADED_FILE_ID: ${{ steps.changed-config.outputs.FILE_ID }}
        run: |
          python get_production_config.py -i ${CHANGED_FILES} -f ${UPDLOADED_FILE_ID}

      - name: Generate diff report compared to production config
        if: steps.changed-files.outputs.any_changed == 'true'
        env:
          UPLOADED_FILE_ID: ${{ steps.changed-config.outputs.FILE_ID }}
        run: |
          PROD_CONFIG_ID=$(jq -r .prod.file_id config_diff.json)
          PROD_CONFIG_NAME=$(jq -r .prod.name config_diff.json)
          UPDATED_CONFIG_NAME=$(jq -r .updated.name config_diff.json)

          icdiff --unified=0 --line-numbers <(dx cat ${PROD_CONFIG_ID}) -L ${PROD_CONFIG_NAME} <(dx cat ${UPLOADED_FILE_ID}) -L ${UPDATED_CONFIG_NAME} | aha > config_diff.html
          echo "Diff report generated"
      - uses: actions/upload-artifact@v4
        with:
          name: diff-report
          path: config_diff.html